apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accounts-service-test-apis
  description: Api for customer and user authorization.
  tags:
    - accounts-service
spec:
  type: openapi
  lifecycle: production
  owner: accounts
  definition:
    $text: ./accountsservice_openapi.yaml
