apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cart-ordering-service-test-apis
  description: Api for cart, coupons and payment operations.
  tags:
    - cart-ordering-service
spec:
  type: openapi
  lifecycle: production
  owner: cart-ordering 
  definition:
    $text: ./cart_ordering_openapi.yaml
