apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: outlet-service-test-apis
  description: Api for outletservice operations.
  tags:
    - outlet-applications
spec:
  type: openapi
  lifecycle: production
  owner: outlet-applications 
  definition:
    $text: ./outletservice_openapi.yaml
